### ISSUE TITLE
[Question] 转载问题

### ISSUE THREAD

**Issue by ddzy** [qq449245884/xiaozhi#59]
看到这些文章很不错: [js是如何工作的](https://github.com/qq449245884/xiaozhi#-javascript是如何工作的系列)!

想问下作者:

我想把这一系列文章转成`PDF`, 然后开源到我的项目(`会备注作者、出处等信息`), 是否可以?

我的项目地址: [fe-necessary-book](https://github.com/ddzy/fe-necessary-book)

**Comment by husky-dot** [comment]
pdf就不行了哈。

**Comment by ddzy** [comment]
> pdf就不行了哈。

好的
